// <auto-generated />
using System;
using BaseCore.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BaseCore.Repository.Migrations
{
    [DbContext(typeof(BaseCoreSalesContext))]
    [Migration("20260531130730_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BaseCore.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SelectedImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("BaseCore.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NameVi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "",
                            IsActive = true,
                            NameEn = "Phone Screen",
                            NameVi = "Màn hình điện thoại"
                        },
                        new
                        {
                            Id = 2,
                            Description = "",
                            IsActive = true,
                            NameEn = "Phone Battery",
                            NameVi = "Pin điện thoại"
                        },
                        new
                        {
                            Id = 3,
                            Description = "",
                            IsActive = true,
                            NameEn = "Phone Camera",
                            NameVi = "Camera điện thoại"
                        },
                        new
                        {
                            Id = 4,
                            Description = "",
                            IsActive = true,
                            NameEn = "Phone Case/Housing",
                            NameVi = "Vỏ điện thoại"
                        },
                        new
                        {
                            Id = 5,
                            Description = "",
                            IsActive = true,
                            NameEn = "Charging Cable",
                            NameVi = "Cáp sạc"
                        },
                        new
                        {
                            Id = 6,
                            Description = "",
                            IsActive = true,
                            NameEn = "Speaker",
                            NameVi = "Loa trong / loa ngoài"
                        },
                        new
                        {
                            Id = 7,
                            Description = "",
                            IsActive = true,
                            NameEn = "Mainboard",
                            NameVi = "Mainboard"
                        },
                        new
                        {
                            Id = 8,
                            Description = "",
                            IsActive = true,
                            NameEn = "IC Component",
                            NameVi = "IC linh kiện"
                        },
                        new
                        {
                            Id = 9,
                            Description = "",
                            IsActive = true,
                            NameEn = "Tempered Glass",
                            NameVi = "Kính cường lực"
                        },
                        new
                        {
                            Id = 10,
                            Description = "",
                            IsActive = true,
                            NameEn = "Repair Tool",
                            NameVi = "Phụ kiện sửa chữa"
                        });
                });

            modelBuilder.Entity("BaseCore.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RelatedId")
                        .HasColumnType("int");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("BaseCore.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CancelReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Profit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ShippingAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalImportCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("BaseCore.Entities.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("FinalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Profit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SelectedImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalImportCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitImportPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("BaseCore.Entities.OrderStockAllocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderDetailId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("StockBatchId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitImportPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderDetailId");

                    b.HasIndex("StockBatchId");

                    b.ToTable("OrderStockAllocations");
                });

            modelBuilder.Entity("BaseCore.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionVi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ImportPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameVi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Specifications")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "EconentTech",
                            CategoryId = 1,
                            Color = "Default",
                            Condition = "New",
                            CreatedAt = new DateTime(2026, 5, 31, 13, 7, 27, 552, DateTimeKind.Utc).AddTicks(6007),
                            DescriptionVi = "Mô tả chi tiết cho Màn hình iPhone 15 Pro Max OLED 1",
                            DiscountPercent = 0m,
                            ImageUrl = "https://placehold.co/400x400?text=Screen",
                            ImportPrice = 2107000.0m,
                            NameEn = "Màn hình iPhone 15 Pro Max OLED 1 (EN)",
                            NameVi = "Màn hình iPhone 15 Pro Max OLED 1",
                            Price = 3010000m,
                            Specifications = "Original 100%, Warranty 12 months",
                            Status = "Active",
                            Stock = 110,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 2,
                            Brand = "EconentTech",
                            CategoryId = 1,
                            Color = "Default",
                            Condition = "New",
                            CreatedAt = new DateTime(2026, 5, 31, 13, 7, 27, 552, DateTimeKind.Utc).AddTicks(6013),
                            DescriptionVi = "Mô tả chi tiết cho Màn hình iPhone 15 Pro Max OLED 2",
                            DiscountPercent = 0m,
                            ImageUrl = "https://placehold.co/400x400?text=Screen",
                            ImportPrice = 2114000.0m,
                            NameEn = "Màn hình iPhone 15 Pro Max OLED 2 (EN)",
                            NameVi = "Màn hình iPhone 15 Pro Max OLED 2",
                            Price = 3020000m,
                            Specifications = "Original 100%, Warranty 12 months",
                            Status = "Active",
                            Stock = 120,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 3,
                            Brand = "EconentTech",
                            CategoryId = 1,
                            Color = "Default",
                            Condition = "New",
                            CreatedAt = new DateTime(2026, 5, 31, 13, 7, 27, 552, DateTimeKind.Utc).AddTicks(6056),
                            DescriptionVi = "Mô tả chi tiết cho Màn hình iPhone 15 Pro Max OLED 3",
                            DiscountPercent = 10m,
                            ImageUrl = "https://placehold.co/400x400?text=Screen",
                            ImportPrice = 2121000.0m,
                            NameEn = "Màn hình iPhone 15 Pro Max OLED 3 (EN)",
                            NameVi = "Màn hình iPhone 15 Pro Max OLED 3",
                            Price = 3030000m,
                            Specifications = "Original 100%, Warranty 12 months",
                            Status = "Active",
                            Stock = 130,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 4,
                            Brand = "EconentTech",
                            CategoryId = 2,
                            Color = "Default",
                            Condition = "New",
                            CreatedAt = new DateTime(2026, 5, 31, 13, 7, 27, 552, DateTimeKind.Utc).AddTicks(6060),
                            DescriptionVi = "Mô tả chi tiết cho Pin iPhone 13 chính hãng 1",
                            DiscountPercent = 0m,
                            ImageUrl = "https://placehold.co/400x400?text=Battery",
                            ImportPrice = 357000.0m,
                            NameEn = "Pin iPhone 13 chính hãng 1 (EN)",
                            NameVi = "Pin iPhone 13 chính hãng 1",
                            Price = 510000m,
                            Specifications = "Original 100%, Warranty 12 months",
                            Status = "Active",
                            Stock = 110,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 5,
                            Brand = "EconentTech",
                            CategoryId = 2,
                            Color = "Default",
                            Condition = "New",
                            CreatedAt = new DateTime(2026, 5, 31, 13, 7, 27, 552, DateTimeKind.Utc).AddTicks(6064),
                            DescriptionVi = "Mô tả chi tiết cho Pin iPhone 13 chính hãng 2",
                            DiscountPercent = 0m,
                            ImageUrl = "https://placehold.co/400x400?text=Battery",
                            ImportPrice = 364000.0m,
                            NameEn = "Pin iPhone 13 chính hãng 2 (EN)",
                            NameVi = "Pin iPhone 13 chính hãng 2",
                            Price = 520000m,
                            Specifications = "Original 100%, Warranty 12 months",
                            Status = "Active",
                            Stock = 120,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 6,
                            Brand = "EconentTech",
                            CategoryId = 2,
                            Color = "Default",
                            Condition = "New",
                            CreatedAt = new DateTime(2026, 5, 31, 13, 7, 27, 552, DateTimeKind.Utc).AddTicks(6068),
                            DescriptionVi = "Mô tả chi tiết cho Pin iPhone 13 chính hãng 3",
                            DiscountPercent = 10m,
                            ImageUrl = "https://placehold.co/400x400?text=Battery",
                            ImportPrice = 371000.0m,
                            NameEn = "Pin iPhone 13 chính hãng 3 (EN)",
                            NameVi = "Pin iPhone 13 chính hãng 3",
                            Price = 530000m,
                            Specifications = "Original 100%, Warranty 12 months",
                            Status = "Active",
                            Stock = 130,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 7,
                            Brand = "EconentTech",
                            CategoryId = 3,
                            Color = "Default",
                            Condition = "New",
                            CreatedAt = new DateTime(2026, 5, 31, 13, 7, 27, 552, DateTimeKind.Utc).AddTicks(6072),
                            DescriptionVi = "Mô tả chi tiết cho Camera sau Samsung S23 Ultra 1",
                            DiscountPercent = 0m,
                            ImageUrl = "https://placehold.co/400x400?text=Camera",
                            ImportPrice = 1057000.0m,
                            NameEn = "Camera sau Samsung S23 Ultra 1 (EN)",
                            NameVi = "Camera sau Samsung S23 Ultra 1",
                            Price = 1510000m,
                            Specifications = "Original 100%, Warranty 12 months",
                            Status = "Active",
                            Stock = 110,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 8,
                            Brand = "EconentTech",
                            CategoryId = 3,
                            Color = "Default",
                            Condition = "New",
                            CreatedAt = new DateTime(2026, 5, 31, 13, 7, 27, 552, DateTimeKind.Utc).AddTicks(6075),
                            DescriptionVi = "Mô tả chi tiết cho Camera sau Samsung S23 Ultra 2",
                            DiscountPercent = 0m,
                            ImageUrl = "https://placehold.co/400x400?text=Camera",
                            ImportPrice = 1064000.0m,
                            NameEn = "Camera sau Samsung S23 Ultra 2 (EN)",
                            NameVi = "Camera sau Samsung S23 Ultra 2",
                            Price = 1520000m,
                            Specifications = "Original 100%, Warranty 12 months",
                            Status = "Active",
                            Stock = 120,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 9,
                            Brand = "EconentTech",
                            CategoryId = 3,
                            Color = "Default",
                            Condition = "New",
                            CreatedAt = new DateTime(2026, 5, 31, 13, 7, 27, 552, DateTimeKind.Utc).AddTicks(6078),
                            DescriptionVi = "Mô tả chi tiết cho Camera sau Samsung S23 Ultra 3",
                            DiscountPercent = 10m,
                            ImageUrl = "https://placehold.co/400x400?text=Camera",
                            ImportPrice = 1071000.0m,
                            NameEn = "Camera sau Samsung S23 Ultra 3 (EN)",
                            NameVi = "Camera sau Samsung S23 Ultra 3",
                            Price = 1530000m,
                            Specifications = "Original 100%, Warranty 12 months",
                            Status = "Active",
                            Stock = 130,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 10,
                            Brand = "EconentTech",
                            CategoryId = 1,
                            Color = "Default",
                            Condition = "New",
                            CreatedAt = new DateTime(2026, 5, 31, 13, 7, 27, 552, DateTimeKind.Utc).AddTicks(6083),
                            DescriptionVi = "Mô tả chi tiết cho Màn hình Samsung A54 1",
                            DiscountPercent = 0m,
                            ImageUrl = "https://placehold.co/400x400?text=Samsung+Screen",
                            ImportPrice = 707000.0m,
                            NameEn = "Màn hình Samsung A54 1 (EN)",
                            NameVi = "Màn hình Samsung A54 1",
                            Price = 1010000m,
                            Specifications = "Original 100%, Warranty 12 months",
                            Status = "Active",
                            Stock = 110,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 11,
                            Brand = "EconentTech",
                            CategoryId = 1,
                            Color = "Default",
                            Condition = "New",
                            CreatedAt = new DateTime(2026, 5, 31, 13, 7, 27, 552, DateTimeKind.Utc).AddTicks(6087),
                            DescriptionVi = "Mô tả chi tiết cho Màn hình Samsung A54 2",
                            DiscountPercent = 0m,
                            ImageUrl = "https://placehold.co/400x400?text=Samsung+Screen",
                            ImportPrice = 714000.0m,
                            NameEn = "Màn hình Samsung A54 2 (EN)",
                            NameVi = "Màn hình Samsung A54 2",
                            Price = 1020000m,
                            Specifications = "Original 100%, Warranty 12 months",
                            Status = "Active",
                            Stock = 120,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 12,
                            Brand = "EconentTech",
                            CategoryId = 1,
                            Color = "Default",
                            Condition = "New",
                            CreatedAt = new DateTime(2026, 5, 31, 13, 7, 27, 552, DateTimeKind.Utc).AddTicks(6090),
                            DescriptionVi = "Mô tả chi tiết cho Màn hình Samsung A54 3",
                            DiscountPercent = 10m,
                            ImageUrl = "https://placehold.co/400x400?text=Samsung+Screen",
                            ImportPrice = 721000.0m,
                            NameEn = "Màn hình Samsung A54 3 (EN)",
                            NameVi = "Màn hình Samsung A54 3",
                            Price = 1030000m,
                            Specifications = "Original 100%, Warranty 12 months",
                            Status = "Active",
                            Stock = 130,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 13,
                            Brand = "EconentTech",
                            CategoryId = 5,
                            Color = "Default",
                            Condition = "New",
                            CreatedAt = new DateTime(2026, 5, 31, 13, 7, 27, 552, DateTimeKind.Utc).AddTicks(6094),
                            DescriptionVi = "Mô tả chi tiết cho Cáp sạc Type-C nhanh 1",
                            DiscountPercent = 0m,
                            ImageUrl = "https://placehold.co/400x400?text=Cable",
                            ImportPrice = 77000.0m,
                            NameEn = "Cáp sạc Type-C nhanh 1 (EN)",
                            NameVi = "Cáp sạc Type-C nhanh 1",
                            Price = 110000m,
                            Specifications = "Original 100%, Warranty 12 months",
                            Status = "Active",
                            Stock = 110,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 14,
                            Brand = "EconentTech",
                            CategoryId = 5,
                            Color = "Default",
                            Condition = "New",
                            CreatedAt = new DateTime(2026, 5, 31, 13, 7, 27, 552, DateTimeKind.Utc).AddTicks(6097),
                            DescriptionVi = "Mô tả chi tiết cho Cáp sạc Type-C nhanh 2",
                            DiscountPercent = 0m,
                            ImageUrl = "https://placehold.co/400x400?text=Cable",
                            ImportPrice = 84000.0m,
                            NameEn = "Cáp sạc Type-C nhanh 2 (EN)",
                            NameVi = "Cáp sạc Type-C nhanh 2",
                            Price = 120000m,
                            Specifications = "Original 100%, Warranty 12 months",
                            Status = "Active",
                            Stock = 120,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 15,
                            Brand = "EconentTech",
                            CategoryId = 5,
                            Color = "Default",
                            Condition = "New",
                            CreatedAt = new DateTime(2026, 5, 31, 13, 7, 27, 552, DateTimeKind.Utc).AddTicks(6100),
                            DescriptionVi = "Mô tả chi tiết cho Cáp sạc Type-C nhanh 3",
                            DiscountPercent = 10m,
                            ImageUrl = "https://placehold.co/400x400?text=Cable",
                            ImportPrice = 91000.0m,
                            NameEn = "Cáp sạc Type-C nhanh 3 (EN)",
                            NameVi = "Cáp sạc Type-C nhanh 3",
                            Price = 130000m,
                            Specifications = "Original 100%, Warranty 12 months",
                            Status = "Active",
                            Stock = 130,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 16,
                            Brand = "EconentTech",
                            CategoryId = 6,
                            Color = "Default",
                            Condition = "New",
                            CreatedAt = new DateTime(2026, 5, 31, 13, 7, 27, 552, DateTimeKind.Utc).AddTicks(6104),
                            DescriptionVi = "Mô tả chi tiết cho Loa ngoài iPhone 12 1",
                            DiscountPercent = 0m,
                            ImageUrl = "https://placehold.co/400x400?text=Speaker",
                            ImportPrice = 182000.0m,
                            NameEn = "Loa ngoài iPhone 12 1 (EN)",
                            NameVi = "Loa ngoài iPhone 12 1",
                            Price = 260000m,
                            Specifications = "Original 100%, Warranty 12 months",
                            Status = "Active",
                            Stock = 110,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 17,
                            Brand = "EconentTech",
                            CategoryId = 6,
                            Color = "Default",
                            Condition = "New",
                            CreatedAt = new DateTime(2026, 5, 31, 13, 7, 27, 552, DateTimeKind.Utc).AddTicks(6129),
                            DescriptionVi = "Mô tả chi tiết cho Loa ngoài iPhone 12 2",
                            DiscountPercent = 0m,
                            ImageUrl = "https://placehold.co/400x400?text=Speaker",
                            ImportPrice = 189000.0m,
                            NameEn = "Loa ngoài iPhone 12 2 (EN)",
                            NameVi = "Loa ngoài iPhone 12 2",
                            Price = 270000m,
                            Specifications = "Original 100%, Warranty 12 months",
                            Status = "Active",
                            Stock = 120,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 18,
                            Brand = "EconentTech",
                            CategoryId = 6,
                            Color = "Default",
                            Condition = "New",
                            CreatedAt = new DateTime(2026, 5, 31, 13, 7, 27, 552, DateTimeKind.Utc).AddTicks(6134),
                            DescriptionVi = "Mô tả chi tiết cho Loa ngoài iPhone 12 3",
                            DiscountPercent = 10m,
                            ImageUrl = "https://placehold.co/400x400?text=Speaker",
                            ImportPrice = 196000.0m,
                            NameEn = "Loa ngoài iPhone 12 3 (EN)",
                            NameVi = "Loa ngoài iPhone 12 3",
                            Price = 280000m,
                            Specifications = "Original 100%, Warranty 12 months",
                            Status = "Active",
                            Stock = 130,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 19,
                            Brand = "EconentTech",
                            CategoryId = 7,
                            Color = "Default",
                            Condition = "New",
                            CreatedAt = new DateTime(2026, 5, 31, 13, 7, 27, 552, DateTimeKind.Utc).AddTicks(6138),
                            DescriptionVi = "Mô tả chi tiết cho Mainboard iPhone 11 1",
                            DiscountPercent = 0m,
                            ImageUrl = "https://placehold.co/400x400?text=Mainboard",
                            ImportPrice = 1407000.0m,
                            NameEn = "Mainboard iPhone 11 1 (EN)",
                            NameVi = "Mainboard iPhone 11 1",
                            Price = 2010000m,
                            Specifications = "Original 100%, Warranty 12 months",
                            Status = "Active",
                            Stock = 110,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 20,
                            Brand = "EconentTech",
                            CategoryId = 7,
                            Color = "Default",
                            Condition = "New",
                            CreatedAt = new DateTime(2026, 5, 31, 13, 7, 27, 552, DateTimeKind.Utc).AddTicks(6142),
                            DescriptionVi = "Mô tả chi tiết cho Mainboard iPhone 11 2",
                            DiscountPercent = 0m,
                            ImageUrl = "https://placehold.co/400x400?text=Mainboard",
                            ImportPrice = 1414000.0m,
                            NameEn = "Mainboard iPhone 11 2 (EN)",
                            NameVi = "Mainboard iPhone 11 2",
                            Price = 2020000m,
                            Specifications = "Original 100%, Warranty 12 months",
                            Status = "Active",
                            Stock = 120,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 21,
                            Brand = "EconentTech",
                            CategoryId = 7,
                            Color = "Default",
                            Condition = "New",
                            CreatedAt = new DateTime(2026, 5, 31, 13, 7, 27, 552, DateTimeKind.Utc).AddTicks(6146),
                            DescriptionVi = "Mô tả chi tiết cho Mainboard iPhone 11 3",
                            DiscountPercent = 10m,
                            ImageUrl = "https://placehold.co/400x400?text=Mainboard",
                            ImportPrice = 1421000.0m,
                            NameEn = "Mainboard iPhone 11 3 (EN)",
                            NameVi = "Mainboard iPhone 11 3",
                            Price = 2030000m,
                            Specifications = "Original 100%, Warranty 12 months",
                            Status = "Active",
                            Stock = 130,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 22,
                            Brand = "EconentTech",
                            CategoryId = 4,
                            Color = "Default",
                            Condition = "New",
                            CreatedAt = new DateTime(2026, 5, 31, 13, 7, 27, 552, DateTimeKind.Utc).AddTicks(6149),
                            DescriptionVi = "Mô tả chi tiết cho Vỏ lưng iPhone 14 Pro 1",
                            DiscountPercent = 0m,
                            ImageUrl = "https://placehold.co/400x400?text=Housing",
                            ImportPrice = 567000.0m,
                            NameEn = "Vỏ lưng iPhone 14 Pro 1 (EN)",
                            NameVi = "Vỏ lưng iPhone 14 Pro 1",
                            Price = 810000m,
                            Specifications = "Original 100%, Warranty 12 months",
                            Status = "Active",
                            Stock = 110,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 23,
                            Brand = "EconentTech",
                            CategoryId = 4,
                            Color = "Default",
                            Condition = "New",
                            CreatedAt = new DateTime(2026, 5, 31, 13, 7, 27, 552, DateTimeKind.Utc).AddTicks(6153),
                            DescriptionVi = "Mô tả chi tiết cho Vỏ lưng iPhone 14 Pro 2",
                            DiscountPercent = 0m,
                            ImageUrl = "https://placehold.co/400x400?text=Housing",
                            ImportPrice = 574000.0m,
                            NameEn = "Vỏ lưng iPhone 14 Pro 2 (EN)",
                            NameVi = "Vỏ lưng iPhone 14 Pro 2",
                            Price = 820000m,
                            Specifications = "Original 100%, Warranty 12 months",
                            Status = "Active",
                            Stock = 120,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 24,
                            Brand = "EconentTech",
                            CategoryId = 4,
                            Color = "Default",
                            Condition = "New",
                            CreatedAt = new DateTime(2026, 5, 31, 13, 7, 27, 552, DateTimeKind.Utc).AddTicks(6156),
                            DescriptionVi = "Mô tả chi tiết cho Vỏ lưng iPhone 14 Pro 3",
                            DiscountPercent = 10m,
                            ImageUrl = "https://placehold.co/400x400?text=Housing",
                            ImportPrice = 581000.0m,
                            NameEn = "Vỏ lưng iPhone 14 Pro 3 (EN)",
                            NameVi = "Vỏ lưng iPhone 14 Pro 3",
                            Price = 830000m,
                            Specifications = "Original 100%, Warranty 12 months",
                            Status = "Active",
                            Stock = 130,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 25,
                            Brand = "EconentTech",
                            CategoryId = 8,
                            Color = "Default",
                            Condition = "New",
                            CreatedAt = new DateTime(2026, 5, 31, 13, 7, 27, 552, DateTimeKind.Utc).AddTicks(6160),
                            DescriptionVi = "Mô tả chi tiết cho IC nguồn iPhone X 1",
                            DiscountPercent = 0m,
                            ImageUrl = "https://placehold.co/400x400?text=IC",
                            ImportPrice = 217000.0m,
                            NameEn = "IC nguồn iPhone X 1 (EN)",
                            NameVi = "IC nguồn iPhone X 1",
                            Price = 310000m,
                            Specifications = "Original 100%, Warranty 12 months",
                            Status = "Active",
                            Stock = 110,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 26,
                            Brand = "EconentTech",
                            CategoryId = 8,
                            Color = "Default",
                            Condition = "New",
                            CreatedAt = new DateTime(2026, 5, 31, 13, 7, 27, 552, DateTimeKind.Utc).AddTicks(6163),
                            DescriptionVi = "Mô tả chi tiết cho IC nguồn iPhone X 2",
                            DiscountPercent = 0m,
                            ImageUrl = "https://placehold.co/400x400?text=IC",
                            ImportPrice = 224000.0m,
                            NameEn = "IC nguồn iPhone X 2 (EN)",
                            NameVi = "IC nguồn iPhone X 2",
                            Price = 320000m,
                            Specifications = "Original 100%, Warranty 12 months",
                            Status = "Active",
                            Stock = 120,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 27,
                            Brand = "EconentTech",
                            CategoryId = 8,
                            Color = "Default",
                            Condition = "New",
                            CreatedAt = new DateTime(2026, 5, 31, 13, 7, 27, 552, DateTimeKind.Utc).AddTicks(6167),
                            DescriptionVi = "Mô tả chi tiết cho IC nguồn iPhone X 3",
                            DiscountPercent = 10m,
                            ImageUrl = "https://placehold.co/400x400?text=IC",
                            ImportPrice = 231000.0m,
                            NameEn = "IC nguồn iPhone X 3 (EN)",
                            NameVi = "IC nguồn iPhone X 3",
                            Price = 330000m,
                            Specifications = "Original 100%, Warranty 12 months",
                            Status = "Active",
                            Stock = 130,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 28,
                            Brand = "EconentTech",
                            CategoryId = 9,
                            Color = "Default",
                            Condition = "New",
                            CreatedAt = new DateTime(2026, 5, 31, 13, 7, 27, 552, DateTimeKind.Utc).AddTicks(6171),
                            DescriptionVi = "Mô tả chi tiết cho Kính cường lực Samsung S22 1",
                            DiscountPercent = 0m,
                            ImageUrl = "https://placehold.co/400x400?text=Glass",
                            ImportPrice = 42000.0m,
                            NameEn = "Kính cường lực Samsung S22 1 (EN)",
                            NameVi = "Kính cường lực Samsung S22 1",
                            Price = 60000m,
                            Specifications = "Original 100%, Warranty 12 months",
                            Status = "Active",
                            Stock = 110,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 29,
                            Brand = "EconentTech",
                            CategoryId = 9,
                            Color = "Default",
                            Condition = "New",
                            CreatedAt = new DateTime(2026, 5, 31, 13, 7, 27, 552, DateTimeKind.Utc).AddTicks(6174),
                            DescriptionVi = "Mô tả chi tiết cho Kính cường lực Samsung S22 2",
                            DiscountPercent = 0m,
                            ImageUrl = "https://placehold.co/400x400?text=Glass",
                            ImportPrice = 49000.0m,
                            NameEn = "Kính cường lực Samsung S22 2 (EN)",
                            NameVi = "Kính cường lực Samsung S22 2",
                            Price = 70000m,
                            Specifications = "Original 100%, Warranty 12 months",
                            Status = "Active",
                            Stock = 120,
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 30,
                            Brand = "EconentTech",
                            CategoryId = 9,
                            Color = "Default",
                            Condition = "New",
                            CreatedAt = new DateTime(2026, 5, 31, 13, 7, 27, 552, DateTimeKind.Utc).AddTicks(6178),
                            DescriptionVi = "Mô tả chi tiết cho Kính cường lực Samsung S22 3",
                            DiscountPercent = 10m,
                            ImageUrl = "https://placehold.co/400x400?text=Glass",
                            ImportPrice = 56000.0m,
                            NameEn = "Kính cường lực Samsung S22 3 (EN)",
                            NameVi = "Kính cường lực Samsung S22 3",
                            Price = 80000m,
                            Specifications = "Original 100%, Warranty 12 months",
                            Status = "Active",
                            Stock = 130,
                            SupplierId = 1
                        });
                });

            modelBuilder.Entity("BaseCore.Entities.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AltText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("BaseCore.Entities.Receipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdminId")
                        .HasColumnType("int");

                    b.Property<string>("CancelReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FromAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ImportPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("ReceiptCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReceiptType")
                        .HasColumnType("int");

                    b.Property<int?>("RequestId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ShippingAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Specifications")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<string>("ToAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalImportAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("ProductId");

                    b.HasIndex("RequestId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Receipts");
                });

            modelBuilder.Entity("BaseCore.Entities.ReturnRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminComment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("ReturnRequests");
                });

            modelBuilder.Entity("BaseCore.Entities.RevenueTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("int");

                    b.Property<string>("OwnerType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ReferenceId")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TransactionType", "ReferenceType", "ReferenceId", "OwnerType", "OwnerId");

                    b.ToTable("RevenueTransactions");
                });

            modelBuilder.Entity("BaseCore.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("BaseCore.Entities.StockBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("QuantityImported")
                        .HasColumnType("int");

                    b.Property<int>("QuantityRemaining")
                        .HasColumnType("int");

                    b.Property<int?>("ReceiptId")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitImportPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ReceiptId");

                    b.HasIndex("SupplierId");

                    b.ToTable("StockBatches");
                });

            modelBuilder.Entity("BaseCore.Entities.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Hanoi, Vietnam",
                            CompanyName = "Tech Supply Co.",
                            ContactName = "Mr. John",
                            CreatedAt = new DateTime(2026, 5, 31, 13, 7, 27, 552, DateTimeKind.Utc).AddTicks(5890),
                            Email = "supplier@econent.com",
                            IsActive = true,
                            Phone = "0988222222",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("BaseCore.Entities.SupplierRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("RejectionReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestedProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("SuggestedPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SupplierId");

                    b.ToTable("SupplierRequests");
                });

            modelBuilder.Entity("BaseCore.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 31, 13, 7, 27, 552, DateTimeKind.Utc).AddTicks(5745),
                            Email = "admin@econent.com",
                            FullName = "System Admin",
                            IsActive = true,
                            PasswordHash = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "0988000000",
                            Role = 0,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 5, 31, 13, 7, 27, 552, DateTimeKind.Utc).AddTicks(5747),
                            Email = "user@econent.com",
                            FullName = "Test User",
                            IsActive = true,
                            PasswordHash = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "0988111111",
                            Role = 1,
                            UserName = "user"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 5, 31, 13, 7, 27, 552, DateTimeKind.Utc).AddTicks(5749),
                            Email = "supplier@econent.com",
                            FullName = "Supplier Demo",
                            IsActive = true,
                            PasswordHash = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Phone = "0988222222",
                            Role = 2,
                            UserName = "supplier"
                        });
                });

            modelBuilder.Entity("BaseCore.Entities.CartItem", b =>
                {
                    b.HasOne("BaseCore.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaseCore.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BaseCore.Entities.Notification", b =>
                {
                    b.HasOne("BaseCore.Entities.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BaseCore.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BaseCore.Entities.Order", b =>
                {
                    b.HasOne("BaseCore.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BaseCore.Entities.OrderDetail", b =>
                {
                    b.HasOne("BaseCore.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaseCore.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BaseCore.Entities.OrderStockAllocation", b =>
                {
                    b.HasOne("BaseCore.Entities.OrderDetail", "OrderDetail")
                        .WithMany("StockAllocations")
                        .HasForeignKey("OrderDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaseCore.Entities.StockBatch", "StockBatch")
                        .WithMany()
                        .HasForeignKey("StockBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrderDetail");

                    b.Navigation("StockBatch");
                });

            modelBuilder.Entity("BaseCore.Entities.Product", b =>
                {
                    b.HasOne("BaseCore.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BaseCore.Entities.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("BaseCore.Entities.ProductImage", b =>
                {
                    b.HasOne("BaseCore.Entities.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BaseCore.Entities.Receipt", b =>
                {
                    b.HasOne("BaseCore.Entities.User", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BaseCore.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BaseCore.Entities.SupplierRequest", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BaseCore.Entities.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Product");

                    b.Navigation("Request");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("BaseCore.Entities.ReturnRequest", b =>
                {
                    b.HasOne("BaseCore.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BaseCore.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BaseCore.Entities.Review", b =>
                {
                    b.HasOne("BaseCore.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BaseCore.Entities.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaseCore.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BaseCore.Entities.StockBatch", b =>
                {
                    b.HasOne("BaseCore.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BaseCore.Entities.Receipt", "Receipt")
                        .WithMany()
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BaseCore.Entities.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Receipt");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("BaseCore.Entities.Supplier", b =>
                {
                    b.HasOne("BaseCore.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BaseCore.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BaseCore.Entities.SupplierRequest", b =>
                {
                    b.HasOne("BaseCore.Entities.User", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BaseCore.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BaseCore.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BaseCore.Entities.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Category");

                    b.Navigation("Product");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("BaseCore.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("BaseCore.Entities.OrderDetail", b =>
                {
                    b.Navigation("StockAllocations");
                });

            modelBuilder.Entity("BaseCore.Entities.Product", b =>
                {
                    b.Navigation("ProductImages");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
